# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='photos/')),
                ('user_type', models.CharField(choices=[('customer', 'CUSTOMER'), ('vendor', 'VENDOR')], default='customer', max_length=6)),
                ('has_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_color', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unitprice', models.FloatField()),
                ('flower_pic', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=30)),
                ('deliver_online', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(upload_to='photos/')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.Vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.CustomUser'),
        ),
    ]
