# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='custom_user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
