# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_auto_20190815_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'CUSTOMER'), ('vendor', 'VENDOR')], default='customer', max_length=8),
        ),
    ]
